/**
 * riven_std.h — C++ implementation of the Riven Standard Library
 * Generated by rivc standard library generator.
 * Include this alongside rivc-generated .cpp files.
 */
#pragma once
#include <string>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <iostream>
#include <cctype>

// ── Math ──────────────────────────────────────────────────────────────────
inline int   abs_i(int x)              { return x < 0 ? -x : x; }
inline double abs_f(double x)          { return std::abs(x); }
inline double sqrt_f(double x)         { return std::sqrt(x); }
inline double pow_f(double b, double e){ return std::pow(b, e); }
inline double floor_f(double x)        { return std::floor(x); }
inline double ceil_f(double x)         { return std::ceil(x); }
inline int   min_i(int a, int b)       { return a < b ? a : b; }
inline int   max_i(int a, int b)       { return a > b ? a : b; }
inline double clamp_f(double v, double lo, double hi) {
    return v < lo ? lo : (v > hi ? hi : v);
}

// ── String ────────────────────────────────────────────────────────────────
inline int str_len(const std::string& s) { return (int)s.size(); }

inline std::string str_upper(std::string s) {
    for (char& c : s) c = (char)std::toupper((unsigned char)c);
    return s;
}
inline std::string str_lower(std::string s) {
    for (char& c : s) c = (char)std::tolower((unsigned char)c);
    return s;
}
inline std::string str_substr(const std::string& s, int start, int len) {
    if (start < 0 || start >= (int)s.size()) return "";
    return s.substr((size_t)start, (size_t)len);
}
inline int str_find(const std::string& haystack, const std::string& needle) {
    auto pos = haystack.find(needle);
    return pos == std::string::npos ? -1 : (int)pos;
}
inline std::string str_concat(const std::string& a, const std::string& b) { return a + b; }

inline std::string int_to_str(int n) { return std::to_string(n); }
inline std::string float_to_str(double f) {
    std::ostringstream ss; ss << f; return ss.str();
}
inline int    str_to_int(const std::string& s)   { return std::stoi(s); }
inline double str_to_float(const std::string& s) { return std::stod(s); }

// ── I/O ───────────────────────────────────────────────────────────────────
inline void print_line(const std::string& s) { std::cout << s << '\n'; }
inline void print_int(int n)                 { std::cout << n << '\n'; }
inline void print_float(double f)            { std::cout << f << '\n'; }
inline std::string read_line() {
    std::string line;
    std::getline(std::cin, line);
    return line;
}

