#include "CodeGen.h"
#include <sstream>
#include <stdexcept>
#include <algorithm>

CodeGenerator::CodeGenerator() : indentLevel(0) {}

// ── Helpers ────────────────────────────────────────────────────────────────

void CodeGenerator::emit(const std::string& s)     { out << s; }
void CodeGenerator::emitLine(const std::string& s) { out << s << "\n"; }
void CodeGenerator::indent()  { ++indentLevel; }
void CodeGenerator::dedent()  { if (indentLevel > 0) --indentLevel; }
std::string CodeGenerator::ind() const { return std::string(indentLevel * 4, ' '); }

std::string CodeGenerator::escapeString(const std::string& s) {
    std::string r;
    for (char c : s) {
        if      (c == '"')  r += "\\\"";
        else if (c == '\\') r += "\\\\";
        else if (c == '\n') r += "\\n";
        else if (c == '\t') r += "\\t";
        else if (c == '\r') r += "\\r";
        else                r += c;
    }
    return r;
}

std::string CodeGenerator::genType(const TypeNode& t) const {
    std::string base;
    if (t.isPointer && t.inner) {
        base = genType(*t.inner) + "*";
    } else {
        if      (t.name == "int")    base = "int";
        else if (t.name == "float")  base = "double";
        else if (t.name == "char")   base = "char";
        else if (t.name == "bool")   base = "bool";
        else if (t.name == "string") base = "std::string";
        else if (t.name == "void")   base = "void";
        else if (t.name == "auto")   base = "auto";
        else                          base = t.name;
    }
    if (t.isArray && !t.isPointer) {
        if (t.arraySize.has_value())
            base += "[" + std::to_string(*t.arraySize) + "]";
        else
            base = "std::vector<" + base + ">";
    }
    if (t.isMut) { /* mut is default in C++, no keyword */ }
    return base;
}

// ── Preamble ──────────────────────────────────────────────────────────────

void CodeGenerator::emitPreamble() {
    emitLine("// ════════════════════════════════════════════════════");
    emitLine("// Generated by Riven Compiler v1.0");
    emitLine("// Riven -> C++ Transpiler Output");
    emitLine("// DO NOT EDIT - Auto-generated file");
    emitLine("// ════════════════════════════════════════════════════");
    emitLine("#include <iostream>");
    emitLine("#include <string>");
    emitLine("#include <vector>");
    emitLine("#include <memory>");
    emitLine("#include <functional>");
    emitLine("#include <stdexcept>");
    emitLine("#include <cstdlib>");
    emitLine("#include <cstring>");
    emitLine("#include <algorithm>");
    emitLine("#include <future>");
    emitLine("#include <sstream>");
    emitLine("#include <cmath>");
    emitLine("#include <cassert>");
    emitLine();
}

// ── Main generate ──────────────────────────────────────────────────────────

std::string CodeGenerator::generate(const Program& prog) {
    emitPreamble();

    // Pass 1: imports
    for (auto& d : prog.decls)
        if (dynamic_cast<const ImportDecl*>(d.get())) genDecl(*d);

    // Pass 2: type declarations (enums/structs/classes/namespaces/traits)
    // Must come BEFORE forward-decls so function signatures can reference them
    emitLine("// -- Type Declarations -----------------------------------------");
    for (auto& d : prog.decls) {
        if (dynamic_cast<const ImportDecl*>(d.get()))    continue;
        if (dynamic_cast<const FuncDecl*>(d.get()))      continue;
        if (dynamic_cast<const GlobalVarDecl*>(d.get())) continue;
        if (dynamic_cast<const ImplDecl*>(d.get()))      continue;
        genDecl(*d);
    }

    // Pass 3: global variables / firm constants
    bool hadGlobal = false;
    for (auto& d : prog.decls) {
        if (auto* gv = dynamic_cast<const GlobalVarDecl*>(d.get())) {
            if (!hadGlobal) {
                emitLine("// -- Global Variables ------------------------------------------");
                hadGlobal = true;
            }
            genGlobalVar(*gv);
        }
    }
    if (hadGlobal) emitLine();

    // Pass 4: function forward-declarations (types already visible now)
    bool hadFwd = false;
    for (auto& d : prog.decls) {
        if (auto* fd = dynamic_cast<const FuncDecl*>(d.get())) {
            if (!fd->body) continue;
            if (!hadFwd) {
                emitLine("// -- Forward Declarations --------------------------------------");
                hadFwd = true;
            }
            emit(ind());
            if (fd->isInline) emit("inline ");
            if (fd->isStatic) emit("static ");
            emit(genType(*fd->returnType) + " " + fd->name + "(");
            for (size_t i = 0; i < fd->params.size(); ++i) {
                auto& p = fd->params[i];
                emit(genType(*p.type));
                if (!p.name.empty()) emit(" " + p.name);
                if (i + 1 < fd->params.size()) emit(", ");
            }
            emitLine(");");
        }
    }
    if (hadFwd) emitLine();

    // Pass 5: impl blocks
    for (auto& d : prog.decls)
        if (dynamic_cast<const ImplDecl*>(d.get())) genDecl(*d);

    // Pass 6: function bodies
    bool hadFuncs = false;
    for (auto& d : prog.decls) {
        if (auto* fd = dynamic_cast<const FuncDecl*>(d.get())) {
            if (!hadFuncs) {
                emitLine("// -- Function Definitions --------------------------------------");
                hadFuncs = true;
            }
            genFuncDecl(*fd);
        }
    }

    // Pass 7: riven core -> int main()
    if (prog.coreEntry) genRivenCore(*prog.coreEntry);
    else emitLine("int main() { return 0; }");

    return out.str();
}

// ── Declarations ──────────────────────────────────────────────────────────

void CodeGenerator::genDecl(const Decl& d) {
    if (auto* imp = dynamic_cast<const ImportDecl*>(&d))         genImportDecl(*imp);
    else if (auto* fd  = dynamic_cast<const FuncDecl*>(&d))      genFuncDecl(*fd);
    else if (auto* sd  = dynamic_cast<const StructDecl*>(&d))    genStructDecl(*sd);
    else if (auto* cd  = dynamic_cast<const ClassDecl*>(&d))     genClassDecl(*cd);
    else if (auto* ed  = dynamic_cast<const EnumDecl*>(&d))      genEnumDecl(*ed);
    else if (auto* nd  = dynamic_cast<const NamespaceDecl*>(&d)) genNamespaceDecl(*nd);
    else if (auto* gv  = dynamic_cast<const GlobalVarDecl*>(&d)) genGlobalVar(*gv);
    else if (auto* td  = dynamic_cast<const TraitDecl*>(&d))     genTraitDecl(*td);
    else if (auto* imd = dynamic_cast<const ImplDecl*>(&d))      genImplDecl(*imd);
}

void CodeGenerator::genImportDecl(const ImportDecl& imp) {
    std::string path = imp.path;
    // Replace Riven extensions with C++ header extensions
    if (path.size() > 3 && path.substr(path.size()-3) == ".rh")
        path = path.substr(0, path.size()-3) + ".h";
    else if (path.size() > 4 && path.substr(path.size()-4) == ".rvh")
        path = path.substr(0, path.size()-4) + ".h";
    // Skip placeholder headers that don't exist (like math.rh in examples)
    emitLine("// #include \"" + path + "\"  // Riven import");
}

void CodeGenerator::genFuncDecl(const FuncDecl& f) {
    emit(ind());
    if (f.isInline) emit("inline ");
    if (f.isStatic) emit("static ");
    if (f.isExtern) emit("extern ");
    emit(genType(*f.returnType) + " " + f.name + "(");
    for (size_t i = 0; i < f.params.size(); ++i) {
        auto& p = f.params[i];
        emit(genType(*p.type));
        if (!p.name.empty()) emit(" " + p.name);
        if (p.defaultVal) { emit(" = "); emit(genExpr(*p.defaultVal)); }
        if (i + 1 < f.params.size()) emit(", ");
    }
    emit(")");
    if (!f.body) { emitLine(";"); return; }
    emitLine(" {");
    indent();
    std::string savedRT = currentReturnType;
    bool savedCore = inCoreEntry;
    currentReturnType = genType(*f.returnType);
    inCoreEntry = false;
    for (auto& st : f.body->stmts) genStmt(*st);
    currentReturnType = savedRT;
    inCoreEntry = savedCore;
    dedent();
    emitLine(ind() + "}");
    emitLine();
}

// Helper: split array type into base + suffix for C-style declarations
// e.g. "int[5]" -> {"int", "[5]"} so we emit "int name[5]" not "int[5] name"
static std::pair<std::string,std::string> splitArrayType(const TypeNode& t, const std::string& computed) {
    if (t.isArray && !t.isPointer) {
        std::string base;
        if      (t.name == "int")    base = "int";
        else if (t.name == "float")  base = "double";
        else if (t.name == "char")   base = "char";
        else if (t.name == "bool")   base = "bool";
        else if (t.name == "string") base = "std::string";
        else                          base = t.name;
        std::string suffix = t.arraySize.has_value()
            ? "[" + std::to_string(*t.arraySize) + "]"
            : "";
        return {base, suffix};
    }
    return {computed, ""};
}

void CodeGenerator::genStructDecl(const StructDecl& s) {
    emitLine(ind() + "struct " + s.name + " {");
    indent();
    for (auto& f : s.fields) {
        emit(ind());
        if (f.type) {
            auto [base, suffix] = splitArrayType(*f.type, genType(*f.type));
            emit(base + " " + f.name + suffix);
        } else {
            emit("int " + f.name);
        }
        if (f.defaultVal) { emit(" = "); emit(genExpr(*f.defaultVal)); }
        emitLine(";");
    }
    if (!s.methods.empty()) emitLine();
    for (auto& m : s.methods) genFuncDecl(*m);
    dedent();
    emitLine(ind() + "};");
    emitLine();
}

void CodeGenerator::genClassDecl(const ClassDecl& c) {
    emit(ind() + "class " + c.name);
    if (!c.base.empty()) emit(" : public " + c.base);
    emitLine(" {");

    auto normAccess = [](const std::string& a) -> std::string {
        if (a == "pub")  return "public";
        if (a == "prot") return "protected";
        // "priv" or empty -> private (class default)
        return "private";
    };

    std::string curAcc = "";
    auto emitAccess = [&](const std::string& a) {
        std::string na = normAccess(a);
        if (na != curAcc) {
            // Dedent back to class level before access label
            out << na << ":\n";
            curAcc = na;
        }
    };

    for (auto& mem : c.members) {
        emitAccess(mem.access);
        auto [base, suffix] = splitArrayType(*mem.type, genType(*mem.type));
        emit(ind() + base + " " + mem.name + suffix);
        if (mem.defaultVal) { emit(" = "); emit(genExpr(*mem.defaultVal)); }
        emitLine(";");
    }
    for (auto& meth : c.methods) {
        emitAccess(meth->access);
        genFuncDecl(*meth);
    }
    emitLine(ind() + "};");
    emitLine();
}

void CodeGenerator::genEnumDecl(const EnumDecl& e) {
    emitLine(ind() + "enum class " + e.name + " {");
    indent();
    for (size_t i = 0; i < e.enumerators.size(); ++i) {
        auto& en = e.enumerators[i];
        emit(ind() + en.name);
        if (en.value) { emit(" = "); emit(genExpr(*en.value)); }
        if (i + 1 < e.enumerators.size()) emit(",");
        emitLine();
    }
    dedent();
    emitLine(ind() + "};");
    emitLine();
}

void CodeGenerator::genNamespaceDecl(const NamespaceDecl& n) {
    emitLine(ind() + "namespace " + n.name + " {");
    indent();
    for (auto& d : n.body) genDecl(*d);
    dedent();
    emitLine(ind() + "} // namespace " + n.name);
    emitLine();
}

void CodeGenerator::genGlobalVar(const GlobalVarDecl& g) {
    emit(ind());
    if (g.isFirm)   emit("const ");
    if (g.isStatic) emit("static ");
    auto [base, suffix] = splitArrayType(*g.type, genType(*g.type));
    emit(base + " " + g.name + suffix);
    if (g.init) { emit(" = "); emit(genExpr(*g.init)); }
    emitLine(";");
}

void CodeGenerator::genTraitDecl(const TraitDecl& t) {
    emitLine(ind() + "// Trait: " + t.name);
    emitLine(ind() + "class " + t.name + " {");
    emitLine("public:");
    indent();
    for (auto& m : t.methods) {
        emit(ind() + "virtual " + genType(*m->returnType) + " " + m->name + "(");
        for (size_t i = 0; i < m->params.size(); ++i) {
            auto& p = m->params[i];
            emit(genType(*p.type));
            if (!p.name.empty()) emit(" " + p.name);
            if (i + 1 < m->params.size()) emit(", ");
        }
        emitLine(") = 0;");
    }
    emitLine(ind() + "virtual ~" + t.name + "() = default;");
    dedent();
    emitLine(ind() + "};");
    emitLine();
}

void CodeGenerator::genImplDecl(const ImplDecl& impl) {
    emitLine(ind() + "// impl " + impl.typeName +
             (impl.traitName.empty() ? "" : " : " + impl.traitName));
    for (auto& m : impl.methods) {
        emit(ind() + genType(*m->returnType) + " " + impl.typeName + "::" + m->name + "(");
        for (size_t j = 0; j < m->params.size(); ++j) {
            auto& p = m->params[j];
            emit(genType(*p.type));
            if (!p.name.empty()) emit(" " + p.name);
            if (j + 1 < m->params.size()) emit(", ");
        }
        emitLine(") {");
        indent();
        if (m->body) for (auto& st : m->body->stmts) genStmt(*st);
        dedent();
        emitLine(ind() + "}");
        emitLine();
    }
}

void CodeGenerator::genRivenCore(const RivenCoreEntry& entry) {
    emitLine("// ── Riven Entry Point ─────────────────────────────");
    emitLine("int main() {");
    indent();
    bool savedCore = inCoreEntry;
    std::string savedRT = currentReturnType;
    inCoreEntry = true;
    currentReturnType = "int";
    for (auto& st : entry.body->stmts) genStmt(*st);
    inCoreEntry = savedCore;
    currentReturnType = savedRT;
    emitLine(ind() + "return 0;");
    dedent();
    emitLine("}");
}

// ── Statements ────────────────────────────────────────────────────────────

void CodeGenerator::genStmt(const Stmt& s) {
    if      (auto* bs = dynamic_cast<const BlockStmt*>(&s))        genBlock(*bs);
    else if (auto* vs = dynamic_cast<const VarDecl*>(&s))          genVarDecl(*vs);
    else if (auto* is = dynamic_cast<const IfStmt*>(&s))           genIf(*is);
    else if (auto* ws = dynamic_cast<const WhileStmt*>(&s))        genWhile(*ws);
    else if (auto* dw = dynamic_cast<const DoWhileStmt*>(&s))      genDoWhile(*dw);
    else if (auto* fs = dynamic_cast<const ForStmt*>(&s))          genFor(*fs);
    else if (auto* rs = dynamic_cast<const ReturnStmt*>(&s))       genReturn(*rs);
    else if (auto* ip = dynamic_cast<const ImprintStmt*>(&s))      genImprint(*ip);
    else if (auto* sq = dynamic_cast<const ScanqStmt*>(&s))        genScanq(*sq);
    else if (auto* ms = dynamic_cast<const MatchStmt*>(&s))        genMatch(*ms);
    else if (auto* ts = dynamic_cast<const TryStmt*>(&s))          genTry(*ts);
    else if (auto* ub = dynamic_cast<const UnsafeBlock*>(&s))      genUnsafe(*ub);
    else if (auto* ab = dynamic_cast<const AsyncBlock*>(&s))       genAsync(*ab);
    else if (auto* ds = dynamic_cast<const DeleteStmt*>(&s))       genDelete(*ds);
    else if (auto* th = dynamic_cast<const ThrowStmt*>(&s))        genThrow(*th);
    else if (dynamic_cast<const BreakStmt*>(&s))                   emitLine(ind() + "break;");
    else if (dynamic_cast<const ContinueStmt*>(&s))                emitLine(ind() + "continue;");
    else if (auto* es = dynamic_cast<const ExprStmt*>(&s)) {
        emitLine(ind() + genExpr(*es->expr) + ";");
    }
}

void CodeGenerator::genBlock(const BlockStmt& b) {
    emitLine(ind() + "{");
    indent();
    for (auto& st : b.stmts) genStmt(*st);
    dedent();
    emitLine(ind() + "}");
}

void CodeGenerator::genVarDecl(const VarDecl& v) {
    emit(ind());
    if (v.isFirm)   emit("const ");
    if (v.isStatic) emit("static ");
    if (v.type) {
        auto [base, suffix] = splitArrayType(*v.type, genType(*v.type));
        emit(base + " " + v.name + suffix);
    } else {
        emit(std::string("auto ") + v.name);
    }
    if (v.init) { emit(" = "); emit(genExpr(*v.init)); }
    emitLine(";");
}

void CodeGenerator::genIf(const IfStmt& i) {
    emit(ind() + "if (");
    emit(genExpr(*i.cond));
    emitLine(") {");
    indent();
    genStmt(*i.thenBranch);
    dedent();
    emit(ind() + "}");

    for (auto& alt : i.altifs) {
        emit(" else if (");
        emit(genExpr(*alt.cond));
        emitLine(") {");
        indent();
        genStmt(*alt.body);
        dedent();
        emit(ind() + "}");
    }

    if (i.elseBranch) {
        emitLine(" else {");
        indent();
        genStmt(*i.elseBranch);
        dedent();
        emitLine(ind() + "}");
    } else {
        emitLine();
    }
}

void CodeGenerator::genWhile(const WhileStmt& w) {
    emitLine(ind() + "while (" + genExpr(*w.cond) + ") {");
    indent();
    genStmt(*w.body);
    dedent();
    emitLine(ind() + "}");
}

void CodeGenerator::genDoWhile(const DoWhileStmt& d) {
    emitLine(ind() + "do {");
    indent();
    genStmt(*d.body);
    dedent();
    emitLine(ind() + "} while (" + genExpr(*d.cond) + ");");
}

void CodeGenerator::genFor(const ForStmt& f) {
    emit(ind() + "for (");
    if (f.init) {
        if (auto* vd = dynamic_cast<const VarDecl*>(f.init.get())) {
            if (vd->isFirm) emit("const ");
            emit(genType(*vd->type) + " " + vd->name);
            if (vd->init) { emit(" = "); emit(genExpr(*vd->init)); }
        } else if (auto* es = dynamic_cast<const ExprStmt*>(f.init.get())) {
            emit(genExpr(*es->expr));
        }
    }
    emit("; ");
    if (f.cond)   emit(genExpr(*f.cond));
    emit("; ");
    if (f.update) emit(genExpr(*f.update));
    emitLine(") {");
    indent();
    genStmt(*f.body);
    dedent();
    emitLine(ind() + "}");
}

void CodeGenerator::genReturn(const ReturnStmt& r) {
    if (!r.value) {
        // 'return fin' with no value
        if (inCoreEntry || currentReturnType == "int") {
            // In riven core (main), bare 'return fin' means return 0
            emitLine(ind() + "return 0;");
        } else {
            emitLine(ind() + "return;");
        }
    } else {
        emit(ind() + "return ");
        emit(genExpr(*r.value));
        emitLine(";");
    }
}

void CodeGenerator::genImprint(const ImprintStmt& i) {
    if (i.args.empty()) {
        emitLine(ind() + "std::cout << std::endl;");
        return;
    }
    emit(ind() + "std::cout");
    for (auto& arg : i.args) {
        emit(" << ");
        emit(genExpr(*arg));
    }
    emitLine(" << std::endl;");
}

void CodeGenerator::genScanq(const ScanqStmt& s) {
    emitLine(ind() + "std::cin >> " + genExpr(*s.target) + ";");
}

void CodeGenerator::genMatch(const MatchStmt& m) {
    // Generate as if-else chain (works for both enums and plain ints)
    emitLine(ind() + "{ // match");
    indent();
    emitLine(ind() + "auto __match_val = (" + genExpr(*m.expr) + ");");
    bool first = true;
    for (auto& c : m.cases) {
        if (!c.pattern) continue; // handle default at end
        emit(ind());
        if (first) emit("if ("); else emit("else if (");
        emit("__match_val == (" + genExpr(*c.pattern) + ")");
        emitLine(") {");
        indent();
        genStmt(*c.body);
        dedent();
        emitLine(ind() + "}");
        first = false;
    }
    // Default case
    for (auto& c : m.cases) {
        if (!c.pattern) {
            if (!first) emit(ind() + "else ");
            emitLine("{");
            indent();
            genStmt(*c.body);
            dedent();
            emitLine(ind() + "}");
        }
    }
    dedent();
    emitLine(ind() + "} // end match");
}

void CodeGenerator::genTry(const TryStmt& t) {
    emitLine(ind() + "try {");
    indent();
    for (auto& st : t.tryBlock->stmts) genStmt(*st);
    dedent();
    emit(ind() + "}");
    for (auto& cc : t.catches) {
        emit(" catch (");
        if (cc.type) emit(genType(*cc.type));
        if (!cc.name.empty()) emit(" " + cc.name);
        emitLine(") {");
        indent();
        for (auto& st : cc.body->stmts) genStmt(*st);
        dedent();
        emit(ind() + "}");
    }
    emitLine();
}

void CodeGenerator::genUnsafe(const UnsafeBlock& u) {
    emitLine(ind() + "{ // unsafe block");
    indent();
    for (auto& st : u.body->stmts) genStmt(*st);
    dedent();
    emitLine(ind() + "} // end unsafe");
}

void CodeGenerator::genAsync(const AsyncBlock& a) {
    emitLine(ind() + "{ // async block");
    emitLine(ind() + "    auto __async_task = std::async(std::launch::async, [&]() -> void {");
    indent(); indent();
    for (auto& st : a.body->stmts) genStmt(*st);
    dedent(); dedent();
    emitLine(ind() + "    });");
    emitLine(ind() + "    __async_task.wait();");
    emitLine(ind() + "}");
}

void CodeGenerator::genDelete(const DeleteStmt& d) {
    emitLine(ind() + "delete " + genExpr(*d.ptr) + ";");
}

void CodeGenerator::genThrow(const ThrowStmt& t) {
    emitLine(ind() + "throw " + genExpr(*t.expr) + ";");
}

// ── Expressions ───────────────────────────────────────────────────────────

std::string CodeGenerator::genExpr(const Expr& e) {
    if (auto* il = dynamic_cast<const IntLiteral*>(&e))
        return std::to_string(il->value);
    if (auto* fl = dynamic_cast<const FloatLiteral*>(&e)) {
        std::ostringstream ss; ss << fl->value; return ss.str();
    }
    if (auto* sl = dynamic_cast<const StringLiteral*>(&e))
        return "std::string(\"" + escapeString(sl->value) + "\")";
    if (auto* cl = dynamic_cast<const CharLiteral*>(&e)) {
        std::string s = "'";
        char c = cl->value;
        if (c == '\'') s += "\\'"; else if (c == '\\') s += "\\\\"; else s += c;
        s += "'"; return s;
    }
    if (auto* bl = dynamic_cast<const BoolLiteral*>(&e))   return bl->value ? "true" : "false";
    if (dynamic_cast<const NullLiteral*>(&e))               return "nullptr";
    if (auto* id = dynamic_cast<const Identifier*>(&e))    return id->name;
    if (auto* be = dynamic_cast<const BinaryExpr*>(&e))    return genBinary(*be);
    if (auto* ue = dynamic_cast<const UnaryExpr*>(&e))     return genUnary(*ue);
    if (auto* ae = dynamic_cast<const AssignExpr*>(&e))    return genAssign(*ae);
    if (auto* ce = dynamic_cast<const CallExpr*>(&e))      return genCall(*ce);
    if (auto* ie = dynamic_cast<const IndexExpr*>(&e))     return genIndex(*ie);
    if (auto* me = dynamic_cast<const MemberExpr*>(&e))    return genMember(*me);
    if (auto* te = dynamic_cast<const TernaryExpr*>(&e))   return genTernary(*te);
    if (auto* ne = dynamic_cast<const NewExpr*>(&e))       return genNew(*ne);
    if (auto* ce2 = dynamic_cast<const CastExpr*>(&e))     return genCast(*ce2);
    if (auto* le = dynamic_cast<const LambdaExpr*>(&e))    return genLambda(*le);
    if (auto* se = dynamic_cast<const SizeofExpr*>(&e))    return genSizeof(*se);
    return "/* unknown_expr */";
}

std::string CodeGenerator::genBinary(const BinaryExpr& b) {
    return "(" + genExpr(*b.left) + " " + b.op + " " + genExpr(*b.right) + ")";
}

std::string CodeGenerator::genUnary(const UnaryExpr& u) {
    std::string op = u.op;
    if (op == "+>") op = "++";
    if (op == "-<") op = "--";
    if (op == "await") return genExpr(*u.operand);
    if (u.postfix) return "(" + genExpr(*u.operand) + op + ")";
    return "(" + op + genExpr(*u.operand) + ")";
}

std::string CodeGenerator::genAssign(const AssignExpr& a) {
    return genExpr(*a.target) + " " + a.op + " " + genExpr(*a.value);
}

std::string CodeGenerator::genCall(const CallExpr& c) {
    std::string result = genExpr(*c.callee) + "(";
    for (size_t i = 0; i < c.args.size(); ++i) {
        result += genExpr(*c.args[i]);
        if (i + 1 < c.args.size()) result += ", ";
    }
    result += ")";
    return result;
}

std::string CodeGenerator::genIndex(const IndexExpr& i) {
    return genExpr(*i.object) + "[" + genExpr(*i.index) + "]";
}

std::string CodeGenerator::genMember(const MemberExpr& m) {
    return genExpr(*m.object) + (m.isArrow ? "->" : ".") + m.member;
}

std::string CodeGenerator::genTernary(const TernaryExpr& t) {
    return "(" + genExpr(*t.cond) + " ? " + genExpr(*t.thenExpr) + " : " + genExpr(*t.elseExpr) + ")";
}

std::string CodeGenerator::genNew(const NewExpr& n) {
    std::string result = "new " + genType(*n.type) + "(";
    for (size_t i = 0; i < n.args.size(); ++i) {
        result += genExpr(*n.args[i]);
        if (i + 1 < n.args.size()) result += ", ";
    }
    result += ")";
    return result;
}

std::string CodeGenerator::genCast(const CastExpr& c) {
    return "static_cast<" + genType(*c.targetType) + ">(" + genExpr(*c.expr) + ")";
}

std::string CodeGenerator::genLambda(const LambdaExpr& l) {
    std::string result = "[&](";
    for (size_t i = 0; i < l.params.size(); ++i) {
        auto& p = l.params[i];
        result += genType(*p.type) + " " + p.name;
        if (i + 1 < l.params.size()) result += ", ";
    }
    result += ")";
    if (l.returnType) result += " -> " + genType(*l.returnType);
    // Inline body generation using a sub-generator
    CodeGenerator sub;
    sub.indentLevel = 1;
    std::ostringstream body;
    body << " {\n";
    for (auto& st : l.body->stmts) {
        sub.out.str(""); sub.out.clear();
        sub.genStmt(*st);
        body << sub.out.str();
    }
    body << "}";
    return result + body.str();
}

std::string CodeGenerator::genSizeof(const SizeofExpr& s) {
    if (s.ofType) return "sizeof(" + genType(*s.ofType) + ")";
    if (s.ofExpr) return "sizeof(" + genExpr(*s.ofExpr) + ")";
    return "sizeof(void*)";
}

